[tool.poetry]
authors = ["Saito Tsutomu <tsutomu7@hotmail.co.jp>"]
classifiers = [
  "Development Status :: 1 - Planning",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Topic :: Software Development",
  "Topic :: Scientific/Engineering",
]
description = "`jcal` is a package for Japanese holiday."
homepage = "https://github.com/SaitoTsutomu/jcal"
license = "MIT"
name = "jcal"
readme = "README.rst"
version = "0.0.15"

[tool.poetry.scripts]
jcal = "jcal:main"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.9.0"
isort = "^5.8.0"
mypy = "^0.812"
pytest = "^6.2.2"

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
