[project]
authors = [{name = "Saito Tsutomu", email = "tsutomu7@hotmail.co.jp"}]
classifiers = [
  "Development Status :: 1 - Planning",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Topic :: Software Development",
  "Topic :: Scientific/Engineering",
]
dependencies = []
description = "`jcal` is a package for Japanese holiday."
license = {text = "Apache-2.0"}
name = "jcal"
readme = "README.md"
requires-python = ">=3.12"
version = "1.1.0"

[project.urls]
homepage = "https://github.com/SaitoTsutomu/jcal"

[project.scripts]
jcal = "jcal:main"

[tool.mypy]
ignore_missing_imports = 1

[tool.ruff]
src = ["src"]

[tool.pytest.ini_options]
addopts = [
  "--strict-markers", # マーカースペルミス対応
  "--strict-config", # 設定ミス対応
  "-ra", # サマリー表示
  "-v", # 詳細表示
  "-x", # 失敗時に終了
  "--capture=no", # 標準出力表示
]

testpaths = "src/tests"

[tool.uv]
dev-dependencies = [
  "holidays>=0.56",
  "jupyterlab>=4.2.5",
  "pytest>=8.3.2",
]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]
